FROM prom/prometheus:v3.2.1
COPY prometheus/prometheus.yml /etc/prometheus/prometheus.yml
ENTRYPOINT ["/bin/sh", "-c"]
CMD ["exec /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.listen-address=0.0.0.0:${PORT:-10000}"]
