apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: https://seat-reservation-prometheus.onrender.com
    isDefault: true
    editable: false